In [1]:
import numpy as np
n=np.array([[0,1,2],[3,4,5],[6,7,8],[9,10,11],[12,13,14],[15,16,17]])

In [8]:
print(n[1,2])

5


In [2]:
import numpy as np
ar=[0,1,2,3]
npar=np.array(ar)
print(npar)

[0 1 2 3]


In [3]:
import numpy as np
import math
def sudoku_solver(side=9,arr=[[5,3,0,0,7,0,0,0,0],[6,0,0,1,9,5,0,0,0],[0,9,8,0,0,0,0,6,0],[8,0,0,0,6,0,0,0,3],[4,0,0,8,0,3,0,0,1],[7,0,0,0,2,0,0,0,6],[0,6,0,0,0,0,2,8,0],[0,0,0,4,1,9,0,0,5],[0,0,0,0,8,0,0,7,9]],row=0,col=0):
        root=int(math.sqrt(side))
        sudoku=np.copy(arr)
        if isSolved(side,sudoku): return [True,sudoku]
        
        #skipping over filled up slots
        while sudoku[row,col]!=0:
            row+=0 if col<(side-1) else 1
            col=(col+1)%side
        
        row_array=sudoku[row,:]
        col_array=sudoku[:,col]
        
        r=row-row%root #row number of 1st element in that internal square
        c=col-col%root #col number of 1st element in that internal square
        #various ways :-
        
        #internal_square_array=np.zeros(side,dtype=np.int8)
        #k=0
        #for i in range(0,root):
        #    for j in range(0,root):
        #        internal_square_array[k]=sudoku[r+i,c+j]
        
        #internal_square_array=np.array([j for i in sudoku[r:r+root] for j in i[c:c+root]])
        
        internal_square_array=sudoku[r:r+root,c:c+root].reshape(side)
        
        
        
        possible=np.array([i for i in range(1,side+1)])
        
        allowed_values=np.setdiff1d(possible,row_array)
        allowed_values=np.setdiff1d(allowed_values,col_array)
        allowed_values=np.setdiff1d(allowed_values,internal_square_array)
        
        for value in allowed_values:
            sudoku[row,col]=value
            row1=row
            col1=col
            row1+=0 if col<(side-1) else 1
            col1=(col1+1)%side
            recieved=sudoku_solver(side,sudoku,row1,col1)
            if recieved[0]==True :
                return recieved
            
        return[False]
        

In [4]:
def isSolved(side=9,arr= np.array([[5, 3, 4, 6, 7, 8, 9, 1, 2],[6, 7, 2, 1, 9, 5, 3, 4, 8],[1, 9, 8, 3, 4, 2, 5, 6, 7],[8, 5, 9, 7, 6, 1, 4, 2, 3],[4, 2, 6, 8, 5, 3, 7, 9, 1],[7, 1, 3, 9, 2, 4, 8, 5, 6],[9, 6, 1, 5, 3, 7, 2, 8, 4],[2, 8, 7, 4, 1, 9, 6, 3, 5],[3, 4, 5, 2, 8, 6, 1, 7, 9]])):
        result=int(side*(side+1)/2)
        
        root=int(math.sqrt(side))
        
        #checking rows
        for i in np.sum(arr,0):
            if i!=result :
                return False
            
        #checking columns
        for i in np.sum(arr,1):
            if i!=result :
                return False
            
        #checking internal squares
        check_arr=np.zeros((root,root),dtype=np.int8)
        for row in range(0,side):
            for col in range(0,side):
                check_arr[int((row-row%root)/root)][int((col-col%root)/root)]+=arr[row][col]
        
        if len([False for i,j in zip(range(root),range(root)) if check_arr[i,j]!=result])>0:
            return False
        
        
        return True
        
                    

In [5]:
arr=np.array([[5, 3, 4, 6, 7, 8, 9, 1, 2],[6, 7, 2, 1, 9, 5, 3, 4, 8],[1, 9, 8, 3, 4, 2, 5, 6, 7],[8, 5, 9, 7, 6, 1, 4, 2, 3],[4, 2, 6, 8, 5, 3, 7, 9, 1],[7, 1, 3, 9, 2, 4, 8, 5, 6],[9, 6, 1, 5, 3, 7, 2, 8, 4],[2, 8, 7, 4, 1, 9, 6, 3, 5],[3, 4, 5, 2, 8, 6, 1, 7, 9]])

print(arr[:,0])

[5 6 1 8 4 7 9 2 3]


In [6]:
isCorrect()

NameError: name 'isCorrect' is not defined

In [ ]:
npar=np.array([0,1,2])
print(npar.shape)

In [ ]:
a=0
a+=0 if 6<5 else 1

In [ ]:
print (a)

In [ ]:
print( [i for i in range(1,10)] )

In [ ]:
arr=np.array([[5, 3, 4, 6, 7, 8, 9, 1, 2],[6, 7, 2, 1, 9, 5, 3, 4, 8],[1, 9, 8, 3, 4, 2, 5, 6, 7],[8, 5, 9, 7, 6, 1, 4, 2, 3],[4, 2, 6, 8, 5, 3, 7, 9, 1],[7, 1, 3, 9, 2, 4, 8, 5, 6],[9, 6, 1, 5, 3, 7, 2, 8, 4],[2, 8, 7, 4, 1, 9, 6, 3, 5],[3, 4, 5, 2, 8, 6, 1, 7, 9]])
r=6
c=6
root=3
intar=[j for i in arr[r:r+root] for j in i[c:c+root]]
print(intar)
print(arr[r:r+root,c:c+root].reshape(root*root))

In [7]:
print(sudoku_solver()[1])

[[5 3 4 6 7 8 9 1 2]
 [6 7 2 1 9 5 3 4 8]
 [1 9 8 3 4 2 5 6 7]
 [8 5 9 7 6 1 4 2 3]
 [4 2 6 8 5 3 7 9 1]
 [7 1 3 9 2 4 8 5 6]
 [9 6 1 5 3 7 2 8 4]
 [2 8 7 4 1 9 6 3 5]
 [3 4 5 2 8 6 1 7 9]]


In [8]:
print (sudoku_solver(4,[[0,0,0,3],[3,2,4,0],[0,4,3,2],[2,0,0,0]])[1])

[[4 1 2 3]
 [3 2 4 1]
 [1 4 3 2]
 [2 3 1 4]]
