In [14]:
import pandas as pd
import numpy as np

In [25]:
football=pd.read_csv('football.csv')

In [26]:
print(type(football))

<class 'pandas.core.frame.DataFrame'>


In [27]:
print(type(football.Goals))

<class 'pandas.core.series.Series'>


In [29]:
print(football.Goals_Allowed)

0     36
1     30
2     45
3     52
4     37
5     38
6     57
7     47
8     53
9     51
10    54
11    47
12    44
13    49
14    57
15    62
16    51
17    64
18    63
19    64
Name: Goals_Allowed, dtype: int64


In [41]:
np_goals=np.array(football.Goals)

79


In [42]:
print(np_goals)


[79 67 87 74 53 66 48 46 49 55 46 35 36 38 45 44 29 41 33 30]


In [43]:
np_goals_allowed=np.array(football.Goals_Allowed)

In [45]:
print(np_goals_allowed)

[36 30 45 52 37 38 57 47 53 51 54 47 44 49 57 62 51 64 63 64]


In [46]:
np_team=np.array(football.Team)

In [49]:
print(np_team)

['Arsenal' 'Liverpool' 'Manchester United' 'Newcastle' 'Leeds' 'Chelsea'
 'West_Ham' 'Aston_Villa' 'Tottenham' 'Blackburn' 'Southampton'
 'Middlesbrough' 'Fulham' 'Charlton' 'Everton' 'Bolton' 'Sunderland'
 'Ipswich' 'Derby' 'Leicester']


In [66]:
np_diff=abs(np_goals[ :]-np_goals_allowed[:])

In [67]:
print(np_diff)

[43 37 42 22 16 28  9  1  4  4  8 12  8 11 12 18 22 23 30 34]


In [68]:
print(np_diff.argmin())

7
